# TODO: turn this down
LineLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/AbcSize:
  Max: 20

Style/GlobalVars:
  Enabled: false
