AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'lib/rbnacl/test_vectors.rb'

#
# Metrics
#

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

#
# Style
#

# TODO: turn this down
LineLength:
  Max: 150

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/GlobalVars:
  Enabled: false
