before_install:
 - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/hauke/dnscurve/ubuntu lucid main'
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnacl-dev

rvm:
  - 1.8.7
  - 1.9.3
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode 

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
