before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnacl

rvm:
  - 1.8.7
  - 1.9.3
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode 

matrix:
  allow_failures:
    - ruby-head
