script: "LD_LIBRARY_PATH=lib bundle exec rake ci"

rvm:
  - 1.8.7
  - 1.9.3
  # - ree # broken on Travis
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode 

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    # - rvm: ree # breaks even allowed_failures on Travis o_O
