script: bundle exec rake ci

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby
  - jruby-9.0.4.0
  - jruby-head
  - rbx-2

env:
  - LIBSODIUM_VERSION=1.0.0 # Minimum supported
  - LIBSODIUM_VERSION=1.0.8 # Latest released

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

notifications:
  irc: "irc.freenode.org#cryptosphere"
